In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('data/test.csv')
df

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q9_2,Q9_3,Q9_4,Q9_5,Q10,Q11,Q12,Q13,Q14_1,Q15
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Attributes - Brand Reputation,Attributes - Health Benefit,Attributes - Caffeine Content,Attributes - Price,Platforms,Units,Purpose,MottoPrice,MottoLikelihood - Likelihood of Switching,MottoFlavor
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID29_2""}","{""ImportId"":""QID29_3""}","{""ImportId"":""QID29_10""}","{""ImportId"":""QID29_11""}","{""ImportId"":""QID30""}","{""ImportId"":""QID31""}","{""ImportId"":""QID32""}","{""ImportId"":""QID42_TEXT""}","{""ImportId"":""QID33_1""}","{""ImportId"":""QID34""}"
2,2023-04-15 13:21:28,2023-04-15 13:23:49,IP Address,174.196.202.163,100,141,True,2023-04-15 13:23:49,R_UEENeM2ghM5uKK5,NaN,...,4,5,3,0,In-Store Ads,Per Unit,Refreshment,4,7,Matcha
3,2023-04-15 13:24:16,2023-04-15 13:27:24,IP Address,107.77.225.125,100,187,True,2023-04-15 13:27:25,R_AzdTD7ACCdSVCTv,NaN,...,1,0,1,3,Word of Mouth,Bulk,Refreshment,0,0,Rooibos
4,2023-04-15 13:24:08,2023-04-15 13:28:14,IP Address,185.216.201.85,100,246,True,2023-04-15 13:28:15,R_2642Y0EiU2ABVzi,NaN,...,3,4,4,4,Word of Mouth,Per Unit,Refreshment,2,8,Matcha
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,2023-04-23 13:35:07,2023-04-23 13:36:37,IP Address,128.197.29.224,100,89,True,2023-04-23 13:36:37,R_3lQDroR045aAk6M,NaN,...,3,3,5,1,In-Store Ads,Per Unit,Energy Boost,$5,3,Matcha
105,2023-04-23 13:34:41,2023-04-23 13:36:56,IP Address,128.197.29.236,100,135,True,2023-04-23 13:36:56,R_3KPE06VqIEladT4,NaN,...,5,5,4,4,In-Store Ads,Per Unit,Refreshment,3,7,Matcha
106,2023-04-23 13:35:03,2023-04-23 13:37:12,IP Address,128.197.29.238,100,128,True,2023-04-23 13:37:13,R_3lyPQPa7kP0tEis,NaN,...,3,4,0,0,Word of Mouth,Per Unit,Refreshment,4,9,Matcha
107,2023-04-23 13:34:09,2023-04-23 13:37:58,IP Address,128.197.29.255,100,229,True,2023-04-23 13:37:59,R_3qD4xaOcxjG2EXM,NaN,...,5,4,4,4,Word of Mouth,Bulk,Refreshment,5,8,Matcha
108,2023-04-23 14:00:08,2023-04-23 14:03:03,IP Address,128.197.29.228,100,175,True,2023-04-23 14:03:04,R_31QRAtBU3ck1VSG,NaN,...,3,4,3,3,Word of Mouth,Per Unit,Refreshment,3.5,7,Matcha

In [3]:
df.columns

Index(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5_1',
       'Q5_2', 'Q5_3', 'Q5_4', 'Q5_5', 'Q5_6', 'Q5_7', 'Q5_8', 'Q6', 'Q7_1',
       'Q8', 'Q9_1', 'Q9_2', 'Q9_3', 'Q9_4', 'Q9_5', 'Q10', 'Q11', 'Q12',
       'Q13', 'Q14_1', 'Q15'],
      dtype='object')

In [4]:
df.IPAddress.nunique()

59

In [10]:
df.IPAddress.unique()

array(['IP Address', '{"ImportId":"ipAddress"}', '174.196.202.163',
       '107.77.225.125', '185.216.201.85', '128.197.29.237',
       '71.233.191.13', '204.8.153.51', '128.197.29.255',
       '128.197.29.232', '128.197.29.225', '174.168.180.88',
       '128.197.29.249', '128.197.29.233', '71.232.45.56',
       '128.197.29.230', '128.197.29.250', '128.197.29.234',
       '128.197.29.240', '128.197.29.243', '128.197.29.251',
       '104.28.39.129', '128.197.29.224', '107.77.223.76',
       '128.197.29.239', '107.77.225.174', '174.242.64.120',
       '107.77.223.106', '128.197.29.228', '128.197.29.235',
       '128.197.29.247', '128.197.29.229', '107.115.17.88',
       '128.197.29.226', '128.197.29.241', '166.198.21.80',
       '172.56.193.104', '128.197.29.238', '128.197.29.231',
       '128.197.29.245', '168.122.146.77', '172.58.221.61',
       '128.197.29.236', '204.8.153.54', '128.197.29.244', '204.8.153.26',
       '128.197.29.227', '128.197.29.254', '128.197.29.242',
       '107.77.225.73', '72.70.63.165', '172.58.223.221', '24.34.189.17',
       '24.34.168.242', '166.198.21.13', '76.19.216.15', '75.147.44.62',
       '172.56.193.40', '128.197.29.246'], dtype=object)

In [24]:
df.IPAddress.value_counts()[df.IPAddress.value_counts().values > 1].__len__()

27

In [23]:
df.loc[df.IPAddress.isin(df.IPAddress.value_counts()[df.IPAddress.value_counts().values > 1].index)]

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q9_2,Q9_3,Q9_4,Q9_5,Q10,Q11,Q12,Q13,Q14_1,Q15
5,2023-04-15 14:44:44,2023-04-15 14:46:59,IP Address,128.197.29.237,100,135,True,2023-04-15 14:47:00,R_1ONMulo6dpFaq04,NaN,...,1,5,5,1,Instagram,Per Unit,Increased Focus,6,7,Matcha
7,2023-04-15 20:17:09,2023-04-15 20:23:01,IP Address,204.8.153.51,100,352,True,2023-04-15 20:23:02,R_2CkqLSHBz13YrE6,NaN,...,3,3,3,3,Word of Mouth,Per Unit,Refreshment,1.2,3,Matcha
8,2023-04-16 14:08:50,2023-04-16 14:12:47,IP Address,128.197.29.255,100,237,True,2023-04-16 14:12:48,R_1gnps0oCxirtcws,NaN,...,1,3,3,4,In-Store Ads,Bulk,Dining Compliments,2.75,1,Rooibos
9,2023-04-16 14:13:23,2023-04-16 14:16:52,IP Address,128.197.29.232,100,209,True,2023-04-16 14:16:53,R_2qgWYgIZBsTNwrC,NaN,...,1,4,4,4,Word of Mouth,Per Unit,Refreshment,2,6,Matcha
10,2023-04-10 17:05:04,2023-04-10 17:05:18,IP Address,128.197.29.225,27,13,False,2023-04-17 17:05:22,R_31HL3P6iG2OqdZg,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,2023-04-23 13:35:07,2023-04-23 13:36:37,IP Address,128.197.29.224,100,89,True,2023-04-23 13:36:37,R_3lQDroR045aAk6M,NaN,...,3,3,5,1,In-Store Ads,Per Unit,Energy Boost,$5,3,Matcha
105,2023-04-23 13:34:41,2023-04-23 13:36:56,IP Address,128.197.29.236,100,135,True,2023-04-23 13:36:56,R_3KPE06VqIEladT4,NaN,...,5,5,4,4,In-Store Ads,Per Unit,Refreshment,3,7,Matcha
106,2023-04-23 13:35:03,2023-04-23 13:37:12,IP Address,128.197.29.238,100,128,True,2023-04-23 13:37:13,R_3lyPQPa7kP0tEis,NaN,...,3,4,0,0,Word of Mouth,Per Unit,Refreshment,4,9,Matcha
107,2023-04-23 13:34:09,2023-04-23 13:37:58,IP Address,128.197.29.255,100,229,True,2023-04-23 13:37:59,R_3qD4xaOcxjG2EXM,NaN,...,5,4,4,4,Word of Mouth,Bulk,Refreshment,5,8,Matcha
108,2023-04-23 14:00:08,2023-04-23 14:03:03,IP Address,128.197.29.228,100,175,True,2023-04-23 14:03:04,R_31QRAtBU3ck1VSG,NaN,...,3,4,3,3,Word of Mouth,Per Unit,Refreshment,3.5,7,Matcha

In [11]:
df.loc[df.IPAddress == '128.197.29.249']

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q9_2,Q9_3,Q9_4,Q9_5,Q10,Q11,Q12,Q13,Q14_1,Q15
12,2023-04-18 10:11:44,2023-04-18 10:16:21,IP Address,128.197.29.249,100,276,True,2023-04-18 10:16:21,R_77hZuFGE51vdIBP,NaN,...,4,4,4,1,Word of Mouth,Per Unit,Refreshment,4,4,Rooibos
76,2023-04-20 20:09:55,2023-04-20 20:13:17,IP Address,128.197.29.249,100,202,True,2023-04-20 20:13:18,R_28Sz1YOP8LDWnWb,NaN,...,3,1,4,1,Word of Mouth,Bulk,Refreshment,3,2,Rooibos
95,2023-04-23 13:27:08,2023-04-23 13:31:06,IP Address,128.197.29.249,100,238,True,2023-04-23 13:31:06,R_1lAfwCbV3iPwIQa,NaN,...,1,3,3,4,TikTok,Bulk,Dining Compliments,1,5,Rooibos
98,2023-04-23 13:30:00,2023-04-23 13:33:40,IP Address,128.197.29.249,100,220,True,2023-04-23 13:33:41,R_2bVRSmd2uedXmd1,NaN,...,1,1,4,4,Word of Mouth,Bulk,Energy Boost,$4,7,Rooibos
102,2023-04-23 13:34:07,2023-04-23 13:36:09,IP Address,128.197.29.249,100,122,True,2023-04-23 13:36:10,R_3PtLg21k1dGi9uE,NaN,...,4,3,1,3,Instagram,Per Unit,Refreshment,5,2,Matcha

In [12]:
df.loc[df.IPAddress == '128.197.29.250']

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q9_2,Q9_3,Q9_4,Q9_5,Q10,Q11,Q12,Q13,Q14_1,Q15
16,2023-04-18 13:22:56,2023-04-18 13:25:56,IP Address,128.197.29.250,100,179,True,2023-04-18 13:25:56,R_OpXa6OIphf8GiFX,NaN,...,4,4,4,4,Word of Mouth,Per Unit,Refreshment,3,8,Rooibos
34,2023-04-19 13:29:25,2023-04-19 13:31:16,IP Address,128.197.29.250,100,110,True,2023-04-19 13:31:16,R_3n0hJ0HtYam7XmQ,NaN,...,1,3,4,4,Word of Mouth,Bulk,Energy Boost,2.5,3,Matcha
43,2023-04-19 13:47:32,2023-04-19 13:50:50,IP Address,128.197.29.250,100,198,True,2023-04-19 13:50:51,R_ZeJIfg0OT7UyYWR,NaN,...,3,4,5,4,Instagram,Per Unit,Energy Boost,$4,2,Matcha
44,2023-04-19 13:49:05,2023-04-19 13:51:00,IP Address,128.197.29.250,100,114,True,2023-04-19 13:51:01,R_UQ48CzapEbZhCHn,NaN,...,0,1,0,3,Instagram,Per Unit,Refreshment,4,7,Matcha
47,2023-04-19 13:58:49,2023-04-19 14:02:43,IP Address,128.197.29.250,100,234,True,2023-04-19 14:02:44,R_2AZnmXI3AVDtvX5,NaN,...,3,3,5,3,Word of Mouth,Per Unit,Refreshment,3,5,Rooibos

In [13]:
df.loc[df.IPAddress == '128.197.29.225']

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q9_2,Q9_3,Q9_4,Q9_5,Q10,Q11,Q12,Q13,Q14_1,Q15
10,2023-04-10 17:05:04,2023-04-10 17:05:18,IP Address,128.197.29.225,27,13,False,2023-04-17 17:05:22,R_31HL3P6iG2OqdZg,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,2023-04-19 15:28:32,2023-04-19 15:33:32,IP Address,128.197.29.225,100,299,True,2023-04-19 15:33:32,R_3ssjgoqvI7ebq7L,NaN,...,0,5,0,4,In-Store Ads,Per Unit,Dining Compliments,2,1,Rooibos
92,2023-04-23 13:26:39,2023-04-23 13:28:59,IP Address,128.197.29.225,100,139,True,2023-04-23 13:28:59,R_2P26sAwncZzv5Ox,NaN,...,4,4,1,4,Instagram,Per Unit,Refreshment,4,5,Matcha
99,2023-04-23 13:30:01,2023-04-23 13:34:12,IP Address,128.197.29.225,100,251,True,2023-04-23 13:34:13,R_2bP27ShTeygUn50,NaN,...,3,4,0,3,Word of Mouth,Bulk,Energy Boost,5,2,Rooibos
103,2023-04-23 13:34:42,2023-04-23 13:36:29,IP Address,128.197.29.225,100,107,True,2023-04-23 13:36:30,R_3EXf8i9JI7ovBVN,NaN,...,4,3,1,5,Word of Mouth,Per Unit,Refreshment,3,9,Matcha

In [5]:
df.drop(columns = ['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage'], inplace=True)

In [10]:
df.drop([1], inplace=True)

In [11]:
df

,ResponseId,Q1,Q2,Q3,Q4,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,...,Q9_3,Q9_4,Q9_5,Q10,Q11,Q12,Q13,Q14_1,Q15,Q15_3_TEXT
0,Response ID,What is your gender?,What is your age?,What is your average annual household income?,How many times per week do you exercise?,"Other than water, which of the following drink...","Other than water, which of the following drink...","Other than water, which of the following drink...","Other than water, which of the following drink...","Other than water, which of the following drink...",...,What attributes influence your selection of dr...,What attributes influence your selection of dr...,What attributes influence your selection of dr...,Which of the following platforms best introduc...,Do you prefer purchasing drinks in bulk or per...,For what purpose do you consume drinks other t...,"Based on the description in Motto,\n\nhow much...","On a scale from 1 to 10, how likely are you to...",Which of the following Motto drinks would you ...,Which of the following Motto drinks would you ...
2,R_ebTly6Krwl7vhol,1,22,4,3,4,4,1,4,4,...,4,3,3,2,1,2,3,8,1,NaN

In [12]:
df.columns

Index(['ResponseId', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5_1', 'Q5_2', 'Q5_3', 'Q5_4',
       'Q5_5', 'Q5_6', 'Q5_7', 'Q5_8', 'Q6', 'Q7_1', 'Q8', 'Q9_1', 'Q9_2',
       'Q9_3', 'Q9_4', 'Q9_5', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14_1', 'Q15',
       'Q15_3_TEXT'],
      dtype='object')

In [8]:
['174.196.202.163',
       '107.77.225.125', '185.216.201.85', '128.197.29.237',
       '71.233.191.13', '204.8.153.51', '128.197.29.255',
       '128.197.29.232', '128.197.29.225', '174.168.180.88',
       '128.197.29.249', '128.197.29.233', '71.232.45.56',
       '128.197.29.230', '128.197.29.250', '128.197.29.234',
       '128.197.29.240', '128.197.29.243', '128.197.29.251',
       '104.28.39.129', '128.197.29.224', '107.77.223.76',
       '128.197.29.239', '107.77.225.174', '174.242.64.120',
       '107.77.223.106', '128.197.29.228', '128.197.29.235',
       '128.197.29.247', '128.197.29.229', '107.115.17.88',
       '128.197.29.226', '128.197.29.241', '166.198.21.80',
       '172.56.193.104', '128.197.29.238', '128.197.29.231',
       '128.197.29.245', '168.122.146.77', '172.58.221.61',
       '128.197.29.236', '204.8.153.54', '128.197.29.244', '204.8.153.26',
       '128.197.29.227', '128.197.29.254', '128.197.29.242',
       '107.77.225.73', '72.70.63.165', '172.58.223.221', '24.34.189.17',
       '24.34.168.242', '166.198.21.13', '76.19.216.15', '75.147.44.62',
       '172.56.193.40', '128.197.29.246'].__len__()

57